### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by eau-de-la-seine** [ghiscoding/angular-markdown-editor#30]
Hi, I have installed your lib:
```
npm install angular-markdown-editor
```

Then I have imported the `AngularMarkdownEditorModule` module, and used the following code in your README.md:
```html
<angular-markdown-editor
  textareaId="editor1" rows="12"
  name="markdownText" [(ngModel)]="markdownText"
  (onChange)="onChange($event.detail.eventData)">
</angular-markdown-editor>
```

But I have this error:
```
core.js:6185 ERROR NullInjectorError: R3InjectorError(AppModule)[config -> config -> config]: 
  NullInjectorError: No provider for config!
    at NullInjector.get (http://localhost:4200/vendor.js:10956:27)
    at R3Injector.get (http://localhost:4200/vendor.js:24672:33)
    at R3Injector.get (http://localhost:4200/vendor.js:24672:33)
    at R3Injector.get (http://localhost:4200/vendor.js:24672:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:42004:33)
    at Object.get (http://localhost:4200/vendor.js:39840:35)
    at getOrCreateInjectable (http://localhost:4200/vendor.js:14734:39)
    at Module.ɵɵdirectiveInject (http://localhost:4200/vendor.js:28571:12)
    at NodeInjectorFactory.AngularMarkdownEditorComponent_Factory [as factory] (http://localhost:4200/vendor.js:73259:204)
    at getNodeInjectable (http://localhost:4200/vendor.js:14879:44)
```

**Please tell us about your environment:**
* Operating System: Linux (distro)
* Browser: all
* Framework/Language: Angular 9

Note: Isn't there a way **to embed the Bootstrap 3 and other dependencies** for people who doesn't want to use these in their project?

Thanks

**Comment by ghiscoding** [comment]
Refer to the [angular-markdown-editor-demo](https://github.com/ghiscoding/angular-markdown-editor-demo), you're most probably missing a few things.

**Comment by engg-aruny** [comment]
For me, it was another dependency called ngx-quill causing the issue and had a conflict.
